LibraryMangementSystem/Controllers/BookController.cs
using LibraryMangementSystem.Models;
using LibraryMangementSystem.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles = "Admin, Librarians")]
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }
        public IActionResult Index()
        {
            List<Book> books = bookRepository.GetAll();
            return View("Index", books);
        }

        public IActionResult Details(int id)
        {
            Book book = bookRepository.GetById(id);
            return View("Details",book);
        }

        public IActionResult Add()
        {
            return View("Add");
        }

        public IActionResult SaveAdd(Book book)
        {
            if(ModelState.IsValid)
            {
                bookRepository.Add(book);
                bookRepository.Save();
                return RedirectToAction("Index");
            }
            return View("Add", book);
        }

        public IActionResult Search(string searchString)
        {
            List<Book> books = bookRepository.GetAll(); // Get all books first

            if (!string.IsNullOrEmpty(searchString))
            {
                // Filter books by title, author, or genre
                books = books.Where(book =>
                    book.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase) ||
                    book.Author.Contains(searchString, StringComparison.OrdinalIgnoreCase) ||
                    book.Genre.Contains(searchString, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }

            return View("Search", books);
        }

        public IActionResult Delete(int id) {
            bookRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

LibraryMangementSystem/Controllers/MemberController.cs
using LibraryMangementSystem.Models;
using LibraryMangementSystem.Repository;
using LibraryMangementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Net;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles = "Members")]
    public class MemberController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMemberRepository memberRepository;
        private readonly ICheckoutRepository checkoutRepository;
        private readonly IBookRepository bookRepository;

        public MemberController(UserManager<ApplicationUser> userManager, IMemberRepository memberRepository, ICheckoutRepository checkoutRepository, IBookRepository bookRepository)
        {
            this.userManager = userManager;
            this.memberRepository = memberRepository;
            this.checkoutRepository = checkoutRepository;
            this.bookRepository = bookRepository;
        }
        public IActionResult MemberInformation()
        {
            string email = User.Identity.Name;
            Member member = memberRepository.GetByEmail(email);
            MemberInformationViewModel memberInformation = new MemberInformationViewModel()
            {
                Address = member.Address,
                DateOfBirth = member.DateOfBirth,
                Email = email,
                FirstName = member.FirstName,
                LastName = member.LastName,
                PhoneNumber = member.PhoneNumber,
            };
            return View("MemberInformation", memberInformation);
        }

        public IActionResult BorrowingHistory()
        {
            string email = User.Identity.Name;
            Member member = memberRepository.GetByEmail(email);
            List<Checkout> checkouts = checkoutRepository.GetByMemberID(member.MemberId);
            List<BorrowingHistoryViewModel> borrowingHistories = new List<BorrowingHistoryViewModel>();
            foreach (var checkout in checkouts)
            {
                BorrowingHistoryViewModel borrowingHistory = new BorrowingHistoryViewModel();
                if (checkout.ReturnDate != null)
                {
                    borrowingHistory.BookName = checkout.Book.Title;
                    borrowingHistory.CheckoutDate = checkout.CheckoutDate;
                    borrowingHistory.DueDate = checkout.DueDate;
                    borrowingHistory.ReturnDate = checkout.ReturnDate;
                    borrowingHistory.PenalityAmount = checkout?.Penalty?.PenaltyAmount ?? 0;
                    borrowingHistories.Add(borrowingHistory);
                }
            }
            return View("BorrowingHistory", borrowingHistories);
        }

        public IActionResult MyBorrowedBook()
        {
            string email = User.Identity.Name;
            Member member = memberRepository.GetByEmail(email);
            List<Checkout> checkouts = checkoutRepository.GetByMemberID(member.MemberId);
            List<BorrowingHistoryViewModel> borrowingHistories = new List<BorrowingHistoryViewModel>();
            foreach (var checkout in checkouts)
            {
                BorrowingHistoryViewModel borrowingHistory = new BorrowingHistoryViewModel();
                if (checkout?.ReturnDate == null)
                {
                    borrowingHistory.BookName = checkout.Book.Title;
                    borrowingHistory.CheckoutDate = checkout.CheckoutDate;
                    borrowingHistory.DueDate = checkout.DueDate;
                    borrowingHistory.ReturnDate = checkout.ReturnDate;

                    // Create a new Penalty object if it doesn't exist
                    Penalty penalty = new Penalty
                    {
                        LateDaysThreshold = 0, // Set your desired threshold here (in days)
                        PenaltyAmount = 2, // Default penalty per day (for example, $2 per day)
                        CheckoutId = checkout.CheckoutId
                    };
                    var lateMinutes = (DateTime.Now - checkout.DueDate).TotalMinutes;
                    // Apply penalty based on minutes
                    if (lateMinutes > penalty.LateDaysThreshold * 1440) // Threshold converted to minutes
                    {
                        var minutesWithPenalty = (decimal)(lateMinutes - (penalty.LateDaysThreshold * 1440)); // Threshold converted to minutes
                        penalty.PenaltyAmount = minutesWithPenalty * (penalty.PenaltyAmount); // Penalty per minute
                    }
                    else
                    {
                        penalty.PenaltyAmount = 0; // No penalty if within the threshold
                    }
                    borrowingHistory.PenalityAmount = penalty.PenaltyAmount;
                    borrowingHistories.Add(borrowingHistory);
                }
            }
            return View("MyBorrowedBook", borrowingHistories);
        }

        public IActionResult BorrowABook()
        {
            List<Book> books = bookRepository.GetAllAvialable();
            return View("BorrowABook", books);
        }

        
        public IActionResult BorrowDetails(int BookId)
        {
            Book book = bookRepository.GetById(BookId);
            return View("BorrowDetails",book);
        }

        [HttpPost]
        public IActionResult BorrowBook(int BookId, DateTime dueDate)
        {
            Book book = bookRepository.GetById(BookId);
            string email = User.Identity.Name;
            Member member = memberRepository.GetByEmail(email);

            var checkout = new Checkout
            {
                BookId = book.BookId,
                MemberId = member.MemberId,
                CheckoutDate = DateTime.Now,
                DueDate = dueDate,
                ReturnDate = null,
                Penalty = null
            };
            book.AvailableCopies -= 1;
            checkoutRepository.Add(checkout);
            checkoutRepository.Save();

            return RedirectToAction("MyBorrowedBook");

        }

        public IActionResult Search(string searchString)
        {
            List<Book> books = bookRepository.GetAllAvialable(); // Get all books first

            if (!string.IsNullOrEmpty(searchString))
            {
                // Filter books by title, author, or genre
                books = books.Where(book =>
                    book.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase) ||
                    book.Author.Contains(searchString, StringComparison.OrdinalIgnoreCase) ||
                    book.Genre.Contains(searchString, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }

            return View("Search", books);
        }
    }
}

LibraryMangementSystem/Controllers/RoleController.cs
using LibraryMangementSystem.Models;
using LibraryMangementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LibraryMangementSystem.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        public async Task<IActionResult> GetAllUsers()
        {
            List<ApplicationUser> users =  userManager.Users.ToList();
            List<UsersAndRolesViewModel> usersAndRolesViewModels = new List<UsersAndRolesViewModel>();
            foreach (var user in users)
            {
                var roles = await userManager.GetRolesAsync(user);
                usersAndRolesViewModels.Add(new UsersAndRolesViewModel { UserName = user.UserName, Roles = roles });
            }
            return View("GetAllUsers", usersAndRolesViewModels);
        }

        public async Task<IActionResult> AssignToRole(string UserName)
        {
            var user = await userManager.FindByNameAsync(UserName);
            var roles = roleManager.Roles.ToList();
            var userRoles = await userManager.GetRolesAsync(user);

            AssignViewModel model = new AssignViewModel
            {
                UserName = user.UserName,
                Roles = roles.Select(role => new RoleSelection
                {
                    RoleName = role.Name
                }).ToList(),
                AssignedRoles = userRoles.ToList()
            };
            return View("AssignToRole", model);
        }

        public async Task<IActionResult> SaveAssign(AssignViewModel model)
        {
            ApplicationUser user = await userManager.FindByNameAsync(model.UserName);
           

            var userRoles = await userManager.GetRolesAsync(user);
            var rolesToAdd = model.AssignedRoles.Except(userRoles);
            var rolesToRemove = userRoles.Except(model.AssignedRoles);

            await userManager.AddToRolesAsync(user, rolesToAdd);
            await userManager.RemoveFromRolesAsync(user, rolesToRemove);

            return RedirectToAction("GetAllUsers");
        }

        public IActionResult AddRole()
        {
            return View("AddRole");
        }

        public async Task<IActionResult> SaveRole(RoleViewModel roleViewModel)
        {
            if(ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();
                role.Name = roleViewModel.RoleName;

                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return View("AddRole");
                }
                
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("AddRole");
        }

    }
}

LibraryMangementSystem/Views/Shared/Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryMangementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryMangementSystem.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-expand-lg  navbar-light bg-light border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <!-- Brand -->
                <a class="navbar-brand fw-bold text-primary" asp-area="" asp-controller="Home" asp-action="Index">
                    📚 Library Management
                </a>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryMangementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryMangementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryMangementSystem.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-expand-lg  navbar-light bg-light border-bottom shadow-sm mb-3">
        <div class="container-fluid">
            <!-- Brand -->
           
                @if (User.IsInRole("Admin") || User.IsInRole("Members") || User.IsInRole("Librarians"))
                {
                    <a class="navbar-brand fw-bold text-primary" asp-area="" asp-controller="Home" asp-action="Index2">
                        📚 Library Management
                    </a>
                }
                else
                {
                    <a class="navbar-brand fw-bold text-primary" asp-area="" asp-controller="Home" asp-action="Index">
                        📚 Library Management
                    </a>
                }


            <!-- Toggler for Mobile -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                    data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" 
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar Items -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  @* *@
                    @if (User.IsInRole("Admin"))
                    {
                            <!-- Home Link -->
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index2">
                                    🏠 Home
                                </a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">📖 Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Checkout" asp-action="Index">🛒 Checkout</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Role" asp-action="GetAllUsers">👥 Roles</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Search">🔍 Search Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">🚪 Sign Out</a>
                        </li>
                    }
                    else if (User.IsInRole("Librarians"))
                    {
                            <!-- Home Link -->
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index2">
                                    🏠 Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">📖 Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Checkout" asp-action="Index">🛒 Checkout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Search">🔍 Search Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">🚪 Sign Out</a>
                            </li>
                    }
                    else if (User.IsInRole("Members"))
                    {
                            <!-- Home Link -->
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index2">
                                    🏠 Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Member" asp-action="MemberInformation">👤 Information</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Member" asp-action="Search">📖 Available Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Member" asp-action="BorrowingHistory">⏳ Borrowing History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Member" asp-action="MyBorrowedBook">📚 Borrowed Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="SignOut" class="text-danger">🚪 Sign Out</a>
                            </li>
                    }
                    else
                    {
                            <!-- Home Link -->
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                                    🏠 Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">👤 Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">📝 Register</a>
                            </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryMangementSystem/Views/Shared/layout3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>